build:
  image: docker
  services:
  - docker:dind
  script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  - if test "$CI_COMMIT_REF_SLUG" = "$CI_DEFAULT_BRANCH"; then CI_COMMIT_REF_SLUG="latest"; fi
  # - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" || true
  - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
      --cache-from "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
      --build-arg ARCH=amd64
  - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  - docker cp "$(docker create "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" /):/bin/external-dns" .
  artifacts:
    untracked: true
